const ADD_FAVORITE = 'ADD_FAVORITE';
const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
const GET_CHARACTER = 'GET_CHARACTER';
const FILTER = 'FILTER';
const ORDER = 'ORDER';
const ALL_CHARACTERS = 'ALL_CHARACTERS';
const SET_ALL_CHARACTERS = 'SET_ALL_CHARACTERS';
const CLEAR_FAVORITES = 'CLEAR_FAVORITES';

export {
	ADD_FAVORITE,
	REMOVE_FAVORITE,
	GET_CHARACTER,
	FILTER,
	ORDER,
	ALL_CHARACTERS,
	SET_ALL_CHARACTERS,
	CLEAR_FAVORITES,
};
